### ISSUE TITLE
Black screen on Google Chrome for Android in VR mode (Cardboard)

### ISSUE THREAD

**Issue by eng1neer** [facebook/react-vr#114] opened 2017-04-20 13:56 UTC
### Description

When running an example WelcomeToVR app (https://facebook.github.io/react-vr/docs/getting-started.html#creating-your-first-project) and entering the VR mode it blinks (a stereo image is shown for a moment) and then shows a black screen with just a Cardboard UI (close button and a settings cog):

![screenshot_20170420-173909](https://cloud.githubusercontent.com/assets/1079094/25234138/4095d6a2-25f2-11e7-98d8-59468f9c3186.png)

#### Expected behavior

An interactive VR scene

#### Actual behavior

Black screen

### Additional Information

* React VR version: 1.0.0
* Operating System: Android 7.1.1
* Graphics Card: Adreno 530 GPU (OnePlus 3T)
* Browser: Chrome for Android 57.0.2987.132 with enabled WebVR flag
* VR Device: OnePlus 3T

WebVR in cardboard mode works ok on aframe on the same setup.

**Comment by andrewimm** [comment] 2017-04-20 16:03
Will investigate as best I can without the same phone. The cardboard support on Chrome for Android is still known to have a number of bugs depending on device and what you're trying to render, we've seen one phone succeed-or-fail at a rate of ~50% with otherwise identical code.

**Comment by infil00p** [comment] 2017-04-21 01:02
I get the same behavior with the Google Pixel on Chrome 57 with the WebVR flag enabled using Daydream.  This issue isn't unique to Cardboard.

**Comment by andrewimm** [comment] 2017-04-21 01:04
Ah, you're right I missed that piece of data. Chrome 57 has known issues that we've been unable to pinpoint. Given that the same application runs fine on Chrome 58 and beyond, we believe it to be an issue with Chrome 57. That said, if we can get around it, we'd like to be able to do so.

**Comment by tinchoforever** [comment] 2017-05-10 23:00
Chrome 58 for Android has the same issue

**Comment by andrewimm** [comment] 2017-05-11 16:35
@tinchoforever which device? Pixel? I haven't seen any issues with Pixel yet on 58 in VR Mode, so it would be good to pinpoint the cause now.

**Comment by alberttoledo** [comment] 2017-05-26 16:30
Any news on this issue? @andrewimm I am having the same problem on Chrome 58 with first generation Pixel.

**Comment by eh3rrera** [comment] 2017-05-31 16:36
I have the same issue using Chrome 58.0.3029.83 for Android, but it works fine on Chrome Canary 61.0.3116.0.

Here's a good article about this:
https://hackernoon.com/how-i-got-a-react-vr-dev-environment-working-with-an-android-cardboard-1fcaf00faebc

**Comment by hongol** [comment] 2017-06-02 03:49
Does this feature only works on Google Pixel phones? Does it work with other Android phone such as Samsung Galaxy or LG?

@andrewimm I am experimenting with LG V10, LG V20 and Samsung Galaxy Note 5 and they are all facing the black screen issue after clicking on View in VR mode.

**Comment by binbingol** [comment] 2017-06-02 04:21
Does this feature only works on Google Pixel phones? Does it work with other Android phone such as Samsung Galaxy or LG?

@andrewimm I am experimenting with LG V10, LG V20 and Samsung Galaxy Note 5 and they are all facing the black screen issue after clicking on View in VR mode.

**Comment by copypasteearth** [comment] 2017-06-21 23:30
i have Samsung galaxy s4 and chrome(58) and i am having the black vr screen issue, i tried Three.js example and the VR works fine

**Comment by andrewimm** [comment] 2017-06-22 00:49
58 has some issues specifically with Samsung graphics chipsets, and I've been able to demonstrate it across a number of WebGL apps (not just React VR).

The good news is that with our recent update to Three.js 85, a fix is available. By turning anti-aliasing off on the canvas, you can get the expected rendering on Samsung devices with Chrome.

When initializing your app, pass an `antialias: false` option, either in `client.js` or in your `index.html`. This should cause the canvas to properly render without any offset or screen-clearing.

**Comment by copypasteearth** [comment] 2017-06-22 01:08
i just did what you said in client.js, and i have the same black screen, its there for like a microsecond then it goes blank
`const vr = new VRInstance(bundle, 'WelcomeToVR', parent, {
    // Add custom options here
    antialias: false,
    ...options,
  });`

**Comment by andrewimm** [comment] 2017-07-04 01:01
As of 1.3.0, antialias is a top-level option at initialization time, and it now defaults to false until this Chrome bug is fixed in stable releases. New or upgraded apps will work on these affected browser versions by default in the meantime.

**Closed by andrewimm** 2017-07-04 01:01 UTC
