### ISSUE TITLE
Incorrect UIView storting / render order

### ISSUE THREAD

**Issue by devotwo** [facebook/react-vr#439] opened 2018-01-30 16:54 UTC
### Description
Possible bug in OVRUI/src/UIView/GuiSys.js  line 55

function matrixDistance(matrixA, matrixB) {
  const x = matrixA.elements[12] - matrixB.elements[12];
  const y = matrixA.elements[13] - matrixB.elements[13];
  const z = matrixA.elements[14] - matrixB.elements[14];
  return Math.sqrt(x * x + _**y * x**_ + z * z);
}

#### Expected behavior
Correct sorting of UI / 3D elements under camera movement.
#### Actual behavior
Wrong depth sorting o UI / 3D elements under camera movement.
### Solution

Correct formula for distance between 2 objects :
 return Math.sqrt(x * x + y * y + z * z);

### Additional Information

* 'react-vr' package version:  react-vr@2.0.0
* 'react-vr-web' package version: react-vr-web@2.0.0
* Operating System:  Windows
* Graphics Card:  Intel
* Browser: Chrome
* VR Device: Out

**Comment by jgwinner** [comment] 2018-01-30 23:01
That makes sense. One trick we used to do back in the day, was to NOT do the Sqrt; if you're just using the result to sort, you don't need to do the extra square root. 

I wonder if this was the cause of the weird transparency problems I noted a while back? I'll try fiddling with that and seeing what happens if I get time.

**Comment by devotwo** [comment] 2018-01-31 08:46
Squered distance would be much faster if we sort a lot of objects.

**Comment by larrylin28** [comment] 2018-01-31 10:21
Thanks for pointing this out! We'll fix this.

**Comment by devotwo** [comment] 2018-01-31 11:44
It would be great if had some control over render order. I've tried to achieve HUD like experience where parts of UI are moving with camera and are rendered with depthTest and depthWrite set to false. In order to get this done properly, render order should be controlled manually. 

Another option would be to have separate THREE.Scene for HUD elements. For this we would need hook in render loop. If there is any post-process effect like bloom or DOF we need this anyway.

**Comment by larrylin28** [comment] 2018-02-01 10:57
We do offer some control of renderOrder, there is a boolean prop `renderGroup` in the view.
And check GuiSys.js for how it's used:

 The sorting of the view elements is customized and handled in frame through the use of the `renderOrder` attribute on the Three.js Object3D. Any object marked as a renderGroup is sorted at a new depth location otherwise objects use their closest parents depth. Order of rendering for objects at the same computed depth is based on pre-traversal order

**Comment by devotwo** [comment] 2018-02-01 13:18
Unfortunately our HUD is more complex then that. We have some video playing there, text, buttons ect. This is where React shines ! HUD is visible only in certain situations and feel good form UX/UI perspective. Only position is locked to camera and not rotation ( not like classical HUD for games). We can interact with it using gaze. 
Same problem would be if interface was attached to hand/controller. It wouldn't look good to have it penetrate 3D scene geometry. 

I did look into GuiSys.js. We use renderGroup however objects are sorted (descretized) by position extracted from world matrix. When you get closer to other non-HUD View's and distance from camera to this object is smaller then HUD element distance and it gets rendered first (on top of hud). 

We could make use of Three.js layers for this.  Render all non-hud elements at default layer 0 na HUD at 1. But this will require changing render loop.

Another option (in GuiSys.js) would be to add special bucket in updateContext.distances for this rendering objects at "zero" depth last.

**Comment by jgwinner** [comment] 2018-02-01 17:43
What happens when it DOES penetrate geometry but is drawn on top? It'll look just *wrong*. Might even cause vergence-accommodation conflict; it'll definitely look unreal and blow the whole VR illusion thing. In 3D you'll see it 'inside' something that isn't transparent; you can't trust your eyes. Has it been tested?

You mention 'It wouldn't look good to have it penetrate 3D scene geometry' but at some point it will - if it's drawn on top, This is, of course, the classic UI issue for VR (menus that are invisible).

If the UI is close to the head, it'll cause eyestrain (vergence-accommodation) regardless (close objects cause this regardless of draw order).

In any event, since you aren't rotating it, can you just wrap it in a view and translate it with everything else? If it gets stuck inside other 3D objects, it'll look natural, and the user could move away from the UI. If it's attached to the controller, then they can just move the menu from 'inside' the object.

Here's a good article although implementation of course is different:

[https://unity3d.com/learn/tutorials/topics/virtual-reality/user-interfaces-vr](https://unity3d.com/learn/tutorials/topics/virtual-reality/user-interfaces-vr) discusses this.

**Comment by jgwinner** [comment] 2018-02-01 17:43
Trying to give you some options - I haven't seen a HUD like this so if you come up with it, it would be interesting to see. I'll beta test if you want :)

**Closed** 2018-05-02 11:07 UTC
