### ISSUE TITLE
Error `"viewConfig" is not defined` trying to use Animated

### ISSUE THREAD

**Issue by darknoon** [facebook/react-vr#138] opened 2017-04-24 02:50 UTC
### Description

I googled for how to use Animated and ended up with code like this. The documentation is really sparse on how to do this, as well.

#### Expected behavior

Background color animates

#### Actual behavior

Error "Plane "viewConfig" is not defined."

### Reproduction

```jsx
// @flow
import React from 'react'
import {
  Box,
  Plane,
  View,
  Pano,
  Animated,
} from 'react-vr';

const groundSize = 100;
const viewerHeight = 2;

type Props = {
  color?: string,
};

type State = {
  fadeAnim: Animated.Value,
}

const AnimatedPlane = Animated.createAnimatedComponent(Plane);

export default class Ground extends React.PureComponent {


  props: Props;

  constructor(props: Props) {
    super(props);
    this.state = {
      fadeAnim: new Animated.Value(0)
    };
  }

  componentDidMount() {
     Animated.timing(          // Uses easing functions
       this.state.fadeAnim,    // The value to drive
       {toValue: 1}            // Configuration
     ).start();                // Don't forget start!
   }


  render() {
    const {color = 'white'} = this.props;
    var animColor = this.state.fadeAnim.interpolate({
        inputRange: [0, 1],
        outputRange: ['rgba(255, 0, 0, 1)', 'rgba(0, 255, 0, 1)']
    });

    return (
      <View>
        <AnimatedPlane
          dimWidth={groundSize}
          dimHeight={groundSize}
          lit={true}
          style={{
            color: animColor,
            transform: [
              {rotateX: -90},
              {translate:[0, 0, -viewerHeight]}
            ],
          }}
        />
      </View>
    );
  }
}
```

### Solution

I tried upgrading to a newer `react-native`, but then I got errors about AccessibiltyContext 

### Additional Information

* React VR version: 1.0.0
* Operating System: Windows
* Graphics Card: GTX 970
* Browser: Firefox Nightly
* VR Device: Oculus Rift

**Comment by mikearmstrong001** [comment] 2017-04-24 08:19
Thanks for reporting the issue is in react-vr rather than react-native. I'll fix this up.

**Comment by mikearmstrong001** [comment] 2017-04-24 15:46
fixed in https://github.com/facebook/react-vr/commit/196396238a0a362942750b24c48e49b6106b96b8

**Comment by darknoon** [comment] 2017-04-24 15:47
Woohoo! 🎉

**Closed by mikearmstrong001** 2017-04-24 15:46 UTC
