### ISSUE TITLE
WelcomeToVR rendering is broken on some versions of Chrome

### ISSUE THREAD

**Issue by sauliusgrigaitis** [facebook/react-vr#252] opened 2017-06-28 10:42 UTC
### Description

We are trying to get WelcomeToVR working. For some reason instead of full screen, it renders only small part of the screen on specific devices (we reproduced it on Xiaomi Mi Redmi Note 3, other phones in the office are Nexus and it works well, but I'm pretty sure there are more phones with this problem).

### Reproduction

Generate project with `react-vr init WelcomeToVR` and try to run then demo on Xiaomi Mi Redmi Note 3 (or some other device that has this issue). You will see only small window at the left bottom:

![Broken Rendering](http://i.imgur.com/5Akw35k.png)

### Additional Information

* 'react-vr' package version: 1.2.0
* 'react-vr-web' package version: 1.2.0
* Operating System: Android  6.0.1
* Browser: Chrome 58.0.3029.83
* Tree.js: we tried different versions without any behaviour change.

**Comment by andrewimm** [comment] 2017-06-29 17:00
This is actually a bug with Chrome 58 + 59 on certain chipsets, which we recently were able to pinpoint. It happens whenever a webgl context is anti-aliased.

I just dug into our code and realized there's no easy way to turn off anti-aliasing, so I'll rush-publish a new version (1.3.0) of our packages that enables it. Until then, you can get around it by modifying the following line in your `ovrui` package:
https://github.com/facebook/react-vr/blob/c5cc04de3c7017e921d6d070b9b88fbdf1831ade/OVRUI/src/Player/Player.js#L293
Change it to say `antialias: false`

I'll update here when new packages are published

**Comment by amberroy** [comment] 2017-06-29 22:43
Updated title to note the issue is with some versions of Chrome and not some devices.  (you may want to use Firefox or Samsung Internet for example)

**Comment by andrewimm** [comment] 2017-07-04 00:56
As of 1.3.0, `antialias` is a top-level option at initialization time, and it now defaults to `false` until this Chrome bug is fixed in stable releases. New or upgraded apps will work on these affected browser versions by default in the meantime.

**Closed by andrewimm** 2017-07-04 00:56 UTC
